<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <title>Login Admin</title>
    <link rel="shortcut icon" href="https://stock.schoolmedia.id/general/logo/faveicon.ico"/>

    <meta name="description" content="User login page"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/bootstrap.css"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

    <!-- text fonts -->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-fonts.css"/>

    <!-- ace styles -->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace.css"/>

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-part2.css"/>
    <![endif]-->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-rtl.css"/>

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-ie.css"/>
    <![endif]-->

    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f01/assets/global/plugins/sweetalert/sweetalert.css"/>

    <!--[if lte IE 8]>
    <script src="https://stock.schoolmedia.id/f02/components/html5shiv/dist/html5shiv.min.js"></script>
    <script src="https://stock.schoolmedia.id/f02/components/respond/dest/respond.min.js"></script>
    <![endif]-->
</head>

<body class="login-layout">
<div class="main-container">
    <div class="main-content">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="login-container">
                    <div class="center">
                        <h1>
                            <i class="ace-icon fa fa-leaf green"></i>
                            <span class="red">PPDB Online</span>
                            <span class="white" id="id-text2">[TAHUN]</span>
                        </h1>
                        <h4 class="blue" id="id-company-text">[DINAS]</h4>
                    </div>

                    <div class="space-6"></div>

                    <div class="position-relative">
                        <div id="login-box" class="login-box visible widget-box no-border">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <h4 class="header blue lighter bigger">
                                        <i class="ace-icon fa fa-coffee green"></i>
                                        Login Panitia
                                    </h4>

                                    <div class="space-6"></div>

                                    <form id="form-login">
                                        <fieldset>
                                            <label class="block clearfix">
														<span class="block input-icon input-icon-right frmInput ">
															<input type="text" class="form-control required" placeholder="NIP/Email" id="txtUsername" autocomplete="off"/>
															<i class="ace-icon fa fa-user frmInput"></i>
														</span>
                                            </label>

                                            <label class="block clearfix">
														<span class="block input-icon input-icon-right frmInput">
															<input type="password" class="form-control required" placeholder="Password" id="txtPass"  />
															<i class="ace-icon fa fa-lock frmInput"></i>
														</span>
                                            </label>

                                            <div class="space"></div>

                                            <div class="clearfix">

                                                {#Semestara
                                                                                                        <button type="button" class="width-35 pull-right btn btn-sm btn-primary">
                                                                                                            <i class="ace-icon fa fa-key"></i>
                                                                                                            <span class="bigger-110">Login</span>
                                                                                                        </button>
                                                #}
                                                <button class="width-35 pull-right btn btn-sm btn-primary" id="btnLogin">
                                                    <i class="ace-icon fa fa-key"></i>
                                                    <span class="bigger-110">Login</span>
                                                </button>
                                            </div>

                                            <div class="space-4"></div>
                                        </fieldset>
                                    </form>

                                </div><!-- /.widget-main -->

                                <div class="toolbar clearfix">
                                    <div>
                                        <a href="#" data-target="#forgot-box" class="forgot-password-link">
                                            <i class="ace-icon fa fa-arrow-left"></i>
                                            Kembali
                                        </a>
                                    </div>

                                    <div>
                                        <a href="#" data-target="#signup-box" class="user-signup-link">
                                            Lupa Password
                                            <i class="ace-icon fa fa-arrow-right"></i>
                                        </a>
                                    </div>
                                </div>
                            </div><!-- /.widget-body -->
                        </div><!-- /.login-box -->
                    </div><!-- /.position-relative -->

                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.main-content -->
</div><!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->
<script src="https://stock.schoolmedia.id/f02/components/jquery/dist/jquery.js"></script>

<!-- <![endif]-->

<!--[if IE]>
<script src="https://stock.schoolmedia.id/f02/components/jquery.1x/dist/jquery.js"></script>
<![endif]-->
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/sweetalert/sweetalert.min.js" type="text/javascript"></script>
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/jquery-validation/js/localization/messages_id.min.js" type="text/javascript"></script>

<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='https://stock.schoolmedia.id/f02/components/_mod/jquery.mobile.custom/jquery.mobile.custom.js'>" + "<" + "/script>");
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#form-login').validate({
            errorElement: 'div',
            errorClass: 'help-block text-danger red',
            rules: {
                name: 'required',

            },
            submitHandler: function () {
                logMasuk();
            }
        })
    })
    function logMasuk() {
        var user = $('#txtUsername').val(),
                pass = $('#txtPass').val();

        swal('Masuk', 'Anda login, selamat bekerja', 'success');
        open('/', '_self');
    }
</script>
</body>
</html>
