<!--
TODO:
Variable:
@Radiogram (JSON_OBJECT)
	@IsClosable:boolean
	@IsiPesan:text
-->
<div class="col-xs-12">
	<div class="alert alert-block alert-success">
		{% if (Radiogram.IsClosable)%}
		<button type="button" class="close" data-dismiss="alert">
			<i class="ace-icon fa fa-times "></i>
		</button>
		{% endif%}
		<!--#CLOSABLE -->
		<div class="h4"><i class="ace-icon fa fa-bullhorn green fa-2x"></i> Pengumuman</div>
		<div>
			<p>
				{% if(Radiogram.IsiPesan=="") %}
				{% include "lipsum.txt" %}
				{% else %}
				{{ Radiogram.IsiPesan|raw}}
				{% endif %}
			</p>
		</div>
	</div>
</div>
