{% extends "depan.phtml" %}

{% block isinya %}
    {% set Sambutan= {
    NamaPenyambut:"Drs. Ciprut",
    JabatanPenyambut:"Walikota Dampit",
    IsiSambutan:"",
    FileFoto:""
    } %}
    {% set Syarat=[
    {Tingkat:"SD",TeksSyarat:"Ini Syarat SD",},
    {Tingkat:"SMP",TeksSyarat:"Ini Syarat SMP"},
    {Tingkat:"SMA",TeksSyarat:"Ini Syarat SMA"},
    {Tingkat:"SMK",TeksSyarat:"Ini Syarat SMK"},
    ] %}
    {% set widgets=[
    {Judul:"Video",IsiWidget:'<iframe src="https://www.youtube.com/embed/ZKxxmxU8GNo" frameborder="0" allowfullscreen></iframe>'},
    {Judul:"Video 2",IsiWidget:'<iframe src="https://www.youtube.com/embed/72MeeEMDXps" frameborder="0" allowfullscreen></iframe>'}
    ] %}

    <div class="row">
        <div class="col-md-8">
            <!-- IF Radiogram object is available -->
            {#{% include "radiogram.phtml" with {Radiogram:{IsClosable:false,IsiPesan:""}} %}#}
            <!-- # RADIOGRAM -->
            <!-- Panel Kiri-->
            {% include "panelkiri.phtml" with {DataTab:{Sambutan:Sambutan,Syarat:Syarat}} %}
            <!-- # PANEL KIRI -->
        </div><!-- /.col kiri -->
        <div class="col-md-4">
            <div class=" visible widget-box " style="border: 1px solid #CCC; padding: 0px">
                <div class="widget-header">Login</div>
                <div class="widget-body">
                    <div class="widget-main text-center">

                        <h4 class="header blue lighter bigger">
                            <i class="ace-icon fa fa-user green"></i>
                            Login Calon Peserta Didik
                        </h4>

                        <div class="space-6"></div>
                        <p> Gunakan <strong>Nomor Pendaftaran dan password</strong> yang anda dapatkan dari Panitia atau dari aplikasi Schoolmedia sekolah
                            Anda:
                        </p>

                        <form action="javascript:void(0)" id="frmLogin">
                            <fieldset>
                                <div class="form-group">
                                    <label class="block clearfix">
                                                        <span
                                                                class="block input-icon input-icon-right">
															<input type="text" class="form-control" placeholder="No Pendaftaran" autocomplete="off" id="nodaf"/>
															<i class="ace-icon fa fa-user"></i>
														</span>
                                    </label>
                                </div>
                                <div class="form-group">
                                    <label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input id="passw" type="password" class="form-control password" data-login="2" placeholder="Password"/>
															<i class="ace-icon fa fa-lock"></i>
														</span>
                                    </label>
                                </div>
                                <div class="space"></div>

                                <div class="clearfix">
                                    <button type="submit" id="btnLogin" class="width-35 pull-right btn btn-sm btn-primary">
                                        <i class="ace-icon fa fa-key"></i>
                                        <span class="bigger-110">Login</span>
                                    </button>
                                </div>

                                <div class="space-4"></div>
                            </fieldset>
                        </form>

                        <!-- /.widget-main -->
                    </div>
                </div>
            </div>

            {% if(widgets!=null) %}
                {% for kotak in widgets %}
                    <div class=" visible widget-box " style="border: 1px solid #CCC; padding: 0px">
                        <div class="widget-header">{{ kotak.Judul }}</div>
                        <div class="widget-body">
                            <div class="widget-main text-center">
                                {{ kotak.IsiWidget|raw }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div><!-- /.col kanan -->
    </div><!-- /.row -->
{% endblock %}

{% block navHeader %}
    <div class="navbar-buttons navbar-header pull-right " role="navigation">
        <ul class="nav ace-nav">
            <li>
                <a class="btn btn-sm btn-success btn-circle" href="/login">
                    <i class="ace-icon fa fa-lock fa-2x"></i>
                </a>

            </li>

        </ul>
    </div>
{% endblock %}
