{% extends "depan.phtml" %}

{% block isinya %}
    {% set Sambutan= {
    NamaPenyambut:"Drs. Ciprut",
    JabatanPenyambut:"Walikota Dampit",
    IsiSambutan:"",
    FileFoto:""
    } %}
    {% set Syarat=[
    {Tingkat:"SD",TeksSyarat:"Ini Syarat SD",},
    {Tingkat:"SMP",TeksSyarat:"Ini Syarat SMP"},
    {Tingkat:"SMA",TeksSyarat:"Ini Syarat SMA"},
    {Tingkat:"SMK",TeksSyarat:"Ini Syarat SMK"},
    ] %}

    <div class="row">
        <div class="col-xs-12">
            {% include "carousel.phtml" %}

        </div>
        <div class="col-md-12">
            <!-- IF Radiogram object is available -->
            {#{% include "radiogram.phtml" with {Radiogram:{IsClosable:false,IsiPesan:""}} %}#}
            <!-- # RADIOGRAM -->
            <!-- Panel Kiri-->
            {% include "panelkiri.phtml" with {DataTab:{Sambutan:Sambutan,Syarat:Syarat}} %}
            <!-- # PANEL KIRI -->
        </div><!-- /.col kiri -->
    </div><!-- /.row -->
{% endblock %}

{% block navHeader %}
    <div class="navbar-buttons navbar-header pull-right " role="navigation">
        <ul class="nav ace-nav">
            <li>
                <a href="login" target="_self" style="background-color: transparent" title="Login" >
                    <i class="ace-icon fa fa-user  fa-2x" style="color: #039BE5;"></i>
                </a>

            </li>

        </ul>
    </div>
{% endblock %}
{% block sidebar %}
    {% include "sidebar.phtml" %}
{% endblock %}