{% extends "depan.phtml" %}
{% block breadcrumbs %}
    {% include "bread.phtml" %}
{% endblock %}
{% block navHeader %}
    {% include "navHeader.phtml" %} {#Untuk atas kanan#}
{% endblock %}
{% block sidebar %}
    {% include "sidebar.phtml" %} {#Untuk menu#}
{% endblock %}
{% block isinya %}
    {% include "header.phtml" %}
    {% if (thePage.rows|length)>=1 %}
        {% for row in thePage.rows %}
            <div class="row">
                {% for div in row.divs %}
                    <div class="{{ div.className }}" id="{{ div.idName }}">
                        {% include "area.phtml" with {komponen:div} %}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}
{% block rightSlider %}
    {% if(rightPanel|length>0) %}
        {% include "rightSlider.phtml" %}
    {% endif %}
{% endblock %}

{% block jscript %}
    <script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.aside.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.modal.aside').ace_aside();

            $('#aside-inside-modal').addClass('aside').ace_aside({container: '#my-modal > .modal-dialog'});

            //$('#top-menu').modal('show')

            $(document).one('ajaxloadstart.page', function (e) {
                //in ajax mode, remove before leaving page
                $('.modal.aside').remove();
                $(window).off('.aside')
            });


            //make content sliders resizable using jQuery UI (you should include jquery ui files)
            //$('#right-menu > .modal-dialog').resizable({handles: "w", grid: [ 20, 0 ], minWidth: 200, maxWidth: 600});
        })
    </script>
{% endblock %}
