<div class="col-xs-12 forLatex"> <div id="test1" class="col-xs-12 "></div></div>
<div class="col-xs-6 forLatex"><textarea id="texting" class="hide col-xs-12"></textarea></div>
<div class="col-xs-6 forLatex"><img id="equation1"/></div>
<div class="col-xs-12">
<textarea class="form-control {{pars.className}} {{addCLass}}" id="{{pars.nmField}}" name="{{pars.nmField}}" placeholder="{{pars.placeholder}}"
          rows="{{jumRows}}" data-init="{{pars.defValue}}">{{pars.defValue}}</textarea>
</div>
<link rel="stylesheet" type="text/css" href="//latex.codecogs.com/css/equation-embed.css" />
<script type="text/javascript" src="//latex.codecogs.com/eqneditor/js/eq_config.js" ></script>
<script type="text/javascript" src="//latex.codecogs.com/eqneditor/js/eq_editor-lite-19.js" ></script>

