<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <title>{{ globalVar.namaApp }}</title>
    <link rel="shortcut icon" href="../asset/images/icon.ico"/>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    <!-- bootstrap & fontawesome -->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/bootstrap.min.css"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

    <!-- page specific plugin styles -->

    <!-- text fonts -->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-fonts.css"/>

    <!-- ace styles -->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace.css" class="ace-main-stylesheet" id="main-ace-style"/>

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-part2.css" class="ace-main-stylesheet"/>
    <![endif]-->
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-skins.css"/>
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-rtl.css"/>

    <!--[if lte IE 9]>
    <link rel="stylesheet" href="https://stock.schoolmedia.id/f02/assets/css/ace-ie.css"/>
    <![endif]-->

    <!-- inline styles related to this page -->

    <!-- ace settings handler -->
    <script src="https://stock.schoolmedia.id/f02/assets/js/ace-extra.js"></script>

    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

    <!--[if lte IE 8]>
    <script src="../components/html5shiv/dist/html5shiv.min.js"></script>
    <script src="../components/respond/dest/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
        #navbar {
            background-color: #f1f1f1;
        }

        #nav-search {
            left: 20%;
            padding-top: 7px;
        }

        .nav-search .nav-search-input {
            border-radius: 0px !important;
        }

        #nav-search-input {
            color: #039BE5;
            border-color: #039BE5;
        }
        .nav-list > li {
            border-style: none;
        }
    </style>

</head>

<body class="{{ pageConfig.skin }}">
<!-- #section:basics/navbar.layout -->
{% if(pageConfig.headerNav) %}
    <div id="navbar" class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-container ace-save-state container" id="navbar-container">
            <!-- #section:basics/sidebar.mobile.toggle -->
            <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
                <span class="sr-only">Toggle sidebar</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>
            </button>

            <!-- /section:basics/sidebar.mobile.toggle -->
            <div class="navbar-header pull-left">
                <!-- #section:basics/navbar.layout.brand -->
                <a href="/" class="navbar-brand">
                    <img src="../asset/images/logo.png" height="25px"/>
                </a>
                <!-- /section:basics/navbar.layout.brand -->

                <!-- #section:basics/navbar.toggle -->

                <!-- /section:basics/navbar.toggle -->
            </div>
            <div id="nav-search" class="navbar-header pull-left">
                <form class="form-search">
      <span class="input-icon input-icon-right">
        <input width="150%" type="text" class="nav-search-input input-sm" id="nav-search-input" autocomplete="off" />
        <i class="ace-icon fa fa-search nav-search-icon" style="color: #039BE5"></i>
      </span>
                </form>
            </div>

            <!-- #section:basics/navbar.dropdown -->
            {% block navHeader %}
                <!--BLOCK UNTUK PROFIL KANAN ATAS -->
            {% endblock %}
            <!-- /section:basics/navbar.dropdown -->
        </div><!-- /.navbar-container -->
    </div>
{% endif %}
<!-- /section:basics/navbar.layout -->
<div class="main-container ace-save-state container" id="main-container">
    <script type="text/javascript">
        try {
            ace.settings.loadState('main-container')
        } catch (e) {
        }
    </script>

    <!-- #section:basics/sidebar -->
    {% block sidebar %}
    {% endblock %}
    <!-- /section:basics/sidebar -->
    <div class="main-content">
        <div class="main-content-inner">
            <!-- #section:basics/content.breadcrumbs -->
            {% block breadcrumbs %}
            {% endblock %}
            <!-- /section:basics/content.breadcrumbs -->
            <div class="page-content">
                <!-- #section:settings.box -->
                {{ linkThis(constant('Twig_Environment::VERSION'),"berandaAdmin")|raw }}
                {% block isinya %}
                    <!-- /section:settings.box -->
                {% endblock %}

                {% block rightSlider %}

                {% endblock %}
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->
    {% if pageConfig.hasFooter %}
        <div class="footer">
            <div class="footer-inner">
                <!-- #section:basics/footer -->
                <div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">{{ globalVar.namaKlien }} </span>
                            {{ globalVar.namaKota }} &copy; {{ globalVar.copyright }}
						</span>

                    &nbsp; &nbsp;
						<span class="action-buttons hide">
							<a href="#">
                                <i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
                            </a>

							<a href="#">
                                <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
                            </a>

							<a href="#">
                                <i class="ace-icon fa fa-rss-square orange bigger-150"></i>
                            </a>
						</span>
                </div>

                <!-- /section:basics/footer -->
            </div>
        </div>
    {% endif %}
    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->
<script src="https://stock.schoolmedia.id/f02/components/jquery/dist/jquery.js"></script>

<!-- <![endif]-->

<!--[if IE]>
<script src="https://stock.schoolmedia.id/f02/components/jquery.1x/dist/jquery.js"></script>
<![endif]-->
<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src='../components/_mod/jquery.mobile.custom/jquery.mobile.custom.js'>" + "<" + "/script>");
</script>
<script src="https://stock.schoolmedia.id/f02/components/bootstrap/dist/js/bootstrap.js"></script>

<!-- page specific plugin scripts -->

<!-- ace scripts -->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.scroller.js"></script>-->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.colorpicker.js"></script>-->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.fileinput.js"></script>-->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.typeahead.js"></script>-->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.wysiwyg.js"></script>-->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.spinner.js"></script>-->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.treeview.js"></script>-->
<!--		<script src="https://stock.schoolmedia.id/f02/assets/js/src/elements.wizard.js"></script>-->
<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.js"></script>
<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.basics.js"></script>
<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.scrolltop.js"></script>
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.ajax-content.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.touch-drag.js"></script>#}
<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.sidebar.js"></script>
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.sidebar-scroll-1.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.submenu-hover.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.widget-box.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.settings.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.settings-rtl.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.settings-skin.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.widget-on-reload.js"></script>#}
{#<script src="https://stock.schoolmedia.id/f02/assets/js/src/ace.searchbox-autocomplete.js"></script>#}

<!-- inline scripts related to this page -->
{% block jscript %}

{% endblock %}

</body>
</html>
