<div id="sidebar" class="sidebar responsive ace-save-state">
    <script type="text/javascript">
        try {
            ace.settings.loadState('sidebar')
        } catch (e) {
        }
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts" style="background-color: #039BE5;color: white">
        <div class="sidebar-shortcuts-large " id="sidebar-shortcuts-large">
            <i class="ace-icon fa fa-th-large"></i>
            Kategori Media

            <!-- /section:basics/sidebar.layout.shortcuts -->
        </div>
        <div class="sidebar-shortcuts-mini hide" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
        {% for menu in menus %}
            {% if (menu.isActive==1) %}
                {% set nmClass='active' %}
            {% endif %}
            {% if (menu.isActive=='') %}
                {% set nmClass='' %}
            {% endif %}
            <li class="{{ nmClass }}">
                <a href="{{ menu.target }}">
                    <button class="btn btn-xs " style="background-color: {{ menu.warna }} !important;border-color:{{ menu.warna }};color: white"><i
                                class="menu-icon fa {{ menu.icon }}"></i></button>
                    <span class="menu-text"> {{ menu.label }} </span>
                </a>
                <b class="arrow"></b>
            </li>
        {% endfor %}
    </ul>

    <!-- #section:basics/sidebar.layout.minimize -->
    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
        <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left"
           data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>

    <!-- /section:basics/sidebar.layout.minimize -->
    <div class="col-xs-12 " style="padding-top: 10px;left: 10px">
        <ul class="nav nav-list">
            <li><i class="ace-icon fa fa-cog"></i> Aplikasi</li>
            <li><a><i class="ace-icon fa fa-exclamation"></i> Informasi</a></li>
        </ul>
    </div>

</div>
