{% extends "utama.phtml" %}

{% block content %}
{{ parent() }}
<h3 class="page-title">Kumpulan Bahan Ajar</h3>
<div class="row">
    <div class="col-md-12">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-heart font-blue"></i>
                    <span class="caption-subject font-blue bold uppercase">Favorit</span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="mt-element-card mt-element-overlay">
                    <div class="row">
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                            <div class="mt-card-item bg-blue-madison mt-element-ribbon">
                                <div class="ribbon ribbon-vertical-left ribbon-color-primary uppercase">
                                    <i class="fa fa-star"></i>
                                </div>

                                <div class="mt-card-avatar mt-overlay-1">
                                    <img src="http://stockfresh.com/files/p/pixxart/m/88/586932_stock-photo-math-exercise.jpg" />
                                    <div class="mt-overlay">
                                        <ul class="mt-info">
                                            <li>
                                                <a class="btn default btn-outline" href="javascript:;">
                                                    Buka
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="mt-card-content bg-font-blue-madison">
                                    <h3 class="mt-card-name">Matematika</h3>
                                    <p class="mt-card-desc ">SMA SMK</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                            <div class="mt-card-item bg-red-intense mt-element-ribbon">
                                <div class="ribbon ribbon-vertical-left ribbon-color-primary uppercase">
                                    <i class="fa fa-star"></i>
                                </div>
                                <div class="mt-card-avatar mt-overlay-1">
                                    <img src="http://previews.123rf.com/images/fikmik/fikmik1105/fikmik110500013/9641915-Science-and-chemistry--Stock-Photo.jpg" />
                                    <div class="mt-overlay">
                                        <ul class="mt-info">
                                            <li>
                                                <a class="btn default btn-outline" href="javascript:;">
                                                    Buka
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="mt-card-content bg-font-red-intense">
                                    <h3 class="mt-card-name">Kimia</h3>
                                    <p class="mt-card-desc ">SMA SMK</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                            <div class="mt-card-item bg-blue-madison mt-element-ribbon">
                                <div class="ribbon ribbon-vertical-left ribbon-color-primary uppercase">
                                    <i class="fa fa-star"></i>
                                </div>

                                <div class="mt-card-avatar mt-overlay-1">
                                    <img src="http://stockfresh.com/files/p/pixxart/m/88/586932_stock-photo-math-exercise.jpg" />
                                    <div class="mt-overlay">
                                        <ul class="mt-info">
                                            <li>
                                                <a class="btn default btn-outline" href="javascript:;">
                                                    Buka
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="mt-card-content bg-font-blue-madison">
                                    <h3 class="mt-card-name">Matematika</h3>
                                    <p class="mt-card-desc ">SMA SMK</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                            <div class="mt-card-item bg-red-intense mt-element-ribbon">
                                <div class="ribbon ribbon-vertical-left ribbon-color-primary uppercase">
                                    <i class="fa fa-star"></i>
                                </div>
                                <div class="mt-card-avatar mt-overlay-1">
                                    <img src="http://previews.123rf.com/images/fikmik/fikmik1105/fikmik110500013/9641915-Science-and-chemistry--Stock-Photo.jpg" />
                                    <div class="mt-overlay">
                                        <ul class="mt-info">
                                            <li>
                                                <a class="btn default btn-outline" href="javascript:;">
                                                    Buka
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="mt-card-content bg-font-red-intense">
                                    <h3 class="mt-card-name">Kimia</h3>
                                    <p class="mt-card-desc ">SMA SMK</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                            <div class="mt-card-item bg-blue-madison mt-element-ribbon">
                                <div class="ribbon ribbon-vertical-left ribbon-color-primary uppercase">
                                    <i class="fa fa-star"></i>
                                </div>

                                <div class="mt-card-avatar mt-overlay-1">
                                    <img src="http://stockfresh.com/files/p/pixxart/m/88/586932_stock-photo-math-exercise.jpg" />
                                    <div class="mt-overlay">
                                        <ul class="mt-info">
                                            <li>
                                                <a class="btn default btn-outline" href="javascript:;">
                                                    Buka
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="mt-card-content bg-font-blue-madison">
                                    <h3 class="mt-card-name">Matematika</h3>
                                    <p class="mt-card-desc ">SMA SMK</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                            <div class="mt-card-item bg-red-intense mt-element-ribbon">
                                <div class="ribbon ribbon-vertical-left ribbon-color-primary uppercase">
                                    <i class="fa fa-star"></i>
                                </div>
                                <div class="mt-card-avatar mt-overlay-1">
                                    <img src="http://previews.123rf.com/images/fikmik/fikmik1105/fikmik110500013/9641915-Science-and-chemistry--Stock-Photo.jpg" />
                                    <div class="mt-overlay">
                                        <ul class="mt-info">
                                            <li>
                                                <a class="btn default btn-outline" href="javascript:;">
                                                    Buka
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="mt-card-content bg-font-red-intense">
                                    <h3 class="mt-card-name">Kimia</h3>
                                    <p class="mt-card-desc ">SMA SMK</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}