<div class="portlet light portlet-fit bordered">
    <div class="portlet-title">
    </div>
    <div class="portlet-body">
        <div class="mt-element-list">
            <div class="mt-list-head list-default green-seagreen">
                <div class="list-head-title-container">
                    <h3 class="list-title uppercase sbold">Soal Saya</h3>
                    <!--                    <div class="list-date">Nov 8, 2015</div>-->
                </div>
            </div>
            <div class="mt-list-container list-default ext-1 group" id="areaListSoal">
                <div class="mt-list-title uppercase">My List<span class="badge badge-default pull-right bg-hover-green-jungle"><a class="font-white" href="javascript:;">
                            <i class="fa fa-plus"></i>
                                                    </a>
                                                </span>
                </div>
            </div>
        </div>
    </div>
</div>
