<script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=/mathJaxConfig.js"></script>
<div class="portlet light bordered">
    <div class="portlet-body form">
        {% include 'frmBuild.phtml' with {theForm:thePage.pageContent.element.forms[0]} %}
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        waitingOff();
        {% include 'summer.js' %}
        {% include 'updatejawabanmultiple.js' %}

    })
</script>