{% extends "utama.phtml" %}
{% block pageSidebar %}
page-sidebar-closed
{%endblock%}
{% block pageSidebarMenu %}
page-sidebar-menu-closed
{%endblock%}

{% block content %}
{{ parent() }}
<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-green-haze">
                    <i class="icon-file font-green-haze"></i>
                    <span class="caption-subject bold uppercase">Pembuatan Paket Soal </span>
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body form">
                {% include 'frmBuild.phtml' with {theForm:thePage.pageContent.element.forms[0]} %}
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block jsFiles %}
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/bootstrap-summernote/summernote.min.js" type="text/javascript"></script>
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/bootstrap-summernote/lang/summernote-id-ID.min.js" type="text/javascript"></script>
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/bootstrap-summernote/summerprint.js" type="text/javascript"></script>
<script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=/mathJaxConfig.js"></script>
{%endblock%}{% block jscript %}
{% include 'summer.js'  %}
{% include 'updatePaket.js'  %}
{%endblock%}