{% extends "utama.phtml" %}
{% block content %}
{{ parent() }}
<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-green-haze">
                    <i class="icon-file font-green-haze"></i>
                    <span class="caption-subject bold uppercase">Pembuatan Soal </span>
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body form">
                {% include 'frmBuild.phtml' with {theForm:thePage.pageContent.element.forms[0]} %}
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block jsFiles %}
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/select2/js/select2.min.js"></script>
<script src="https://stock.schoolmedia.id/f01/assets/global/plugins/select2/js/i18n/id.js"></script>
{%endblock%}{% block jscript %}
{% include 'soalbaru.js'  %}
{%endblock%}