{% extends "utama.phtml" %}
{% block content %}
{{ parent() }}
<div class="row">
<div class="col-lg-12">
    <div class="portlet light  bordered">
        <div class="portlet-title">
            <div class="caption">
            </div>
        </div>
        <div class="portlet-body">
            <div class="mt-element-list">
                <div class="mt-list-head list-simple ext-1 font-white bg-blue-chambray">
                    <div class="list-head-title-container">
<!--                        <div class="list-date">Nov 8, 2015</div>-->
                        <h3 class="list-title">
                            <i class=" icon-layers "></i>
                            Data Ujian</h3>
                    </div>
                </div>
                <div class="mt-list-container list-simple ext-1 group">
                    <a class="list-toggle-container" data-toggle="collapse" href="#completed-simple" aria-expanded="false">
                        <div class="list-toggle done uppercase"> Belum berjalan
                            <span class="badge badge-default pull-right bg-white font-green bold">{{thePage.pageContent.nextUjian|length}}</span>
                        </div>
                    </a>
                    <div class="panel-collapse collapse in" id="completed-simple">
                        <ul>
                            {% for ujian in thePage.pageContent.nextUjian%}
                            <li class="mt-list-item done" data-itemujian="{{ujian.KD_UJIAN}}">
                                <div class="list-icon-container">
                                    <i class="icon-check"></i>
                                </div>
                                <div class="list-datetime"> <button class="btn btn-sm btn-danger btnHapus" data-a="{{ujian.KD_UJIAN}}"><i class="fa fa-times"></i> </button> </div>
                                <div class="list-item-content">
                                    <h3 class="uppercase">
                                        <a href="/ujian/pilihsoal/{{ujian.KD_UJIAN}}">{{ujian.NAMA_UJIAN}}</a>
                                    </h3>
                                </div>
                            </li>
                            {%endfor%}
                        </ul>
                    </div>
                    <a class="list-toggle-container " data-toggle="collapse" href="#pending-simple" aria-expanded="false">
                        <div class="list-toggle uppercase"> Sedang berjalan (menu pengawas)
                            <span class="badge badge-default pull-right bg-white font-dark bold">{{thePage.pageContent.progUjian|length}}</span>
                        </div>
                    </a>
                    <div class="panel-collapse collapse " id="pending-simple">
                        <ul>
                            {% for ujian in thePage.pageContent.progUjian%}
                            <li class="mt-list-item done" data-itemujian="{{ujian.KD_UJIAN}}">
                                <div class="list-icon-container">
                                    <i class="icon-check"></i>
                                </div>
                                <div class="list-item-content">
                                    <h3 class="uppercase">
                                        <a href="/ujian/manage/{{ujian.KD_UJIAN}}">{{ujian.NAMA_UJIAN}}</a>
                                    </h3>
                                </div>
                            </li>
                            {%endfor%}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}
{% block jscript %}

{% include 'listUjian.js' with {params:thePage.pageContent} %}

{%endblock%}