{% extends "utama.phtml" %}

{% block content %}
{{ parent() }}
<h3 class="page-title">Matematika <small>untuk SMA SMK</small></h3>
<div class="row">
    <div class="col-md-12">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-body">
                <div class="mt-element-list">
                    <div class="mt-list-head list-news ext-1 bg-font-blue-madison bg-blue-madison ">
                        <div class="list-head-title-container">
                            <h3 class="list-title bg-font-yellow-crusta">Materi Pembelajaran tersimpan</h3>
                        </div>
                        <div class="list-count pull-right bg-yellow-saffron">2</div>
                    </div>
                    <div class="mt-list-container list-news ext-2">
                        <ul>
                            <li class="mt-list-item">
                                <div class="list-icon-container">
                                    <a href="javascript:;">
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </div>
                                <div class="list-thumb">
                                    <a href="javascript:;">
                                        <img alt="" src="http://cdn.vogue.es/uploads/images/thumbs/es/vog/2/s/2016/05/vogue_news_797041250_620x.jpg" />
                                    </a>
                                </div>
                                <div class="list-datetime bold uppercase font-yellow-casablanca"> Metty Mutmainah </div>
                                <div class="list-item-content">
                                    <h3 class="uppercase bold">
                                        <a href="javascript:;">Persamaan dan Pertidaksamaan Linear</a>
                                    </h3>
                                    <p>Memahami dan Menemukan Konsep nilai mutlak.</p>
                                </div>
                            </li>
                            <li class="mt-list-item">
                                <div class="list-icon-container">
                                    <a href="javascript:;">
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </div>
                                <div class="list-thumb">
                                    <a href="javascript:;">
                                        <img alt="" src="../assets/global/img/portfolio/600x600/10.jpg" />
                                    </a>
                                </div>
                                <div class="list-datetime bold uppercase font-yellow-casablanca"> 8 Nov, 2015 </div>
                                <div class="list-item-content">
                                    <h3 class="uppercase bold">
                                        <a href="javascript:;">Latest news on Metronic</a>
                                    </h3>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elementum gravida mauris, a tincidunt dolor porttitor eu. </p>
                                </div>
                            </li>
                            <li class="mt-list-item">
                                <div class="list-icon-container">
                                    <a href="javascript:;">
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                </div>
                                <div class="list-thumb">
                                    <a href="javascript:;">
                                        <img alt="" src="../assets/global/img/portfolio/600x600/08.jpg" />
                                    </a>
                                </div>
                                <div class="list-datetime bold uppercase font-dark"> 8 Nov, 2015 </div>
                                <div class="list-item-content">
                                    <h3 class="uppercase bold">
                                        <a href="javascript:;">Latest news on Metronic</a>
                                    </h3>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elementum gravida mauris, a tincidunt dolor porttitor eu. </p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}