{% extends "utama.phtml" %}

{% block content %}
{{ parent() }}
<h3 class="page-title">Koleksi Soal</h3>
<div class="row">
    <div class="col-md-6">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">Soal Saya</div>
            <div class="portlet-body">
                <div class="mt-element-list">
                    <div class="mt-list-head list-default green-seagreen">
                        <div class="list-head-title-container">
                            <h3 class="list-title uppercase sbold">Berdasarkan mata pelajaran</h3>
                            <!--                    <div class="list-date">Nov 8, 2015</div>-->
                        </div>
                    </div>
                    <div class="mt-list-container list-default ext-1 group" id="areaListSoal">
                        <div class="mt-list-title uppercase">Tambah baru<span class="badge badge-default pull-right bg-hover-green-jungle">
                                <a class="font-white" href="/butirsoal/baru">
                                    <i class="fa fa-plus"></i>
                                </a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block jscript %}
{% include 'daftarSoal.js' with {target:"areaListSoal"} %}
{%endblock%}