{% extends "utama.phtml" %}
{% block pageSidebar %}
page-sidebar-closed
{%endblock%}
{% block pageSidebarMenu %}
page-sidebar-menu-closed
{%endblock%}

{% block content %}
{{ parent() }}

<h3 class="page-title">Pemilihan Soal </h3>
<div class="row">
    <div class="col-md-12">
        <div class="portlet red-sunglo box">
            <div class="portlet-title ">
                <div class="caption"> {{thePage.pageContent.ujian.NAMA_UJIAN}}</div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-hover">
                    <tr>
                        <th width="30%">Mata Pelajaran</th>
                        <td colspan="2">{{thePage.pageContent.ujian.NM_MATA_PELAJARAN}}</td>
                    </tr>
                    <tr>
                        <th>Tanggal</th>
                        <td colspan="2">{{thePage.pageContent.ujian.TANGGAL_MULAI}} hingga {{thePage.pageContent.ujian.TANGGAL_AKHIR}}</td>
                    </tr>
                    <tr>
                        <th>Durasi ujian</th>
                        <td colspan="2">{{thePage.pageContent.ujian.DURASI_UJIAN}} menit</td>
                    </tr>
                    <tr>
                        <th>Jumlah Soal</th>
                        <td>{{thePage.pageContent.ujian.JUMLAH_SOAL}} dari total <span id="spanTotal">{{thePage.pageContent.jumlahSoal}}</span> soal
                            {{thePage.pageContent.ujian.NM_SCOPE_SOAL|lower}}
                        </td>
                        <td width="10%">
                            <button class="btn btn-sm blue-sharp hide" id="btnSoal">Detail Soal</button>
                        </td>
                    </tr>
                    <tr>
                        <th>Jumlah Peserta</th>
                        <td><span id="spanPeserta">{{thePage.pageContent.jumlahPeserta}}</span> peserta didik</td>
                        <td width="10%">
                            <button class="btn btn-sm green-soft hide" id="btnPeserta">Detail Peserta</button>
                        </td>
                    </tr>
                    <tr>
                        <th>Kode Token</th>
                        <td><strong>{{thePage.pageContent.ujian.KODE_TOKEN}}</strong> diberikan apabila ujian telah siap dimulai</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet blue-sharp box" >
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-list"></i>Soal </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="mt-element-list">
                    <div class="mt-list-container list-todo">
                        <div class="list-todo-line"></div>
                        <ul>
                            {% set theNum=1 %}
                            {% for quests in thePage.pageContent.theSoal %}
                            <li class="mt-list-item" data-itemsoal="{{quests.KD_SOAL}}">
                                <div class="list-todo-icon bg-white font-dark">
                                    {{theNum}}
                                </div>
                                <div class="list-todo-item grey">
                                    <a class="list-toggle-container" data-toggle="collapse" href="#task-{{theNum}}" aria-expanded="false">
                                        <div class="list-toggle done uppercase">
                                            <div class="list-toggle-title bold">{{quests.JUDUL_SOAL}}</div>
                                        </div>
                                    </a>
                                    <div class="task-list panel-collapse collapse" id="task-{{theNum}}">
                                        <p style="padding-left: 12px">{{quests.teksSoal|raw}}</p>
                                        <ul>
                                            {%for answer in quests.answers %}
                                            <li class="task-list-item ">
                                                <div class="task-icon"><i class="fa fa-circle-o"></i> </div>
                                                <div class="task-content">
                                                    {{answer.textJawab|raw}}
                                                </div>
                                            </li>
                                            {% endfor%}
                                        </ul>
                                        <div class="task-footer bg-grey-cascade">
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <a class="task-trash hapusSoal" data-a="{{quests.KD_SOAL}}"  href="javascript:;">
                                                        <i class="fa fa-trash"></i> Hapus Soal ini
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% set theNum=theNum+1 %}
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="portlet green-soft box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-users"></i>Peserta</div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <ul class="nav nav-tabs tabs-left" id="ulRombel">
                        </ul>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-9">
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="tab_6_1">
                                <table class="table table-striped table-hover" id="tableSiswa">
                                    <thead>
                                    <tr>
                                        <th width="10%" class="text-center">Pilih <br/><input type="checkbox" class="form-control" id="pilAll"></th>
                                        <th width="20%">NIS</th>
                                        <th>Nama Peserta Didik</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block jsFiles %}
<script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=/mathJaxConfig.js"></script>
{% endblock%}

{% block jscript %}
{% include 'listSoalUjian.js' with {params:thePage.pageContent.ujian} %}

{%endblock%}