{% extends "utama.phtml" %}

{% block content %}
{{ parent() }}
<h3 class="page-title">Materi Pembelajaran</h3>
<div class="row">
    <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit round  bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-chart font-dark"></i>
                    <span class="caption-subject font-dark sbold uppercase"> Persamaan dan Pertidaksamaan Linear</span>
                    </span>
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                    <a href="" class="fullscreen"> </a>
                </div>

                <div class="actions">
                    <div class="btn-group">
                        <a class="btn red btn-outline btn-circle" href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Tools </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="javascript:;"> Trivia </a>
                            </li>
                            <li>
                                <a href="javascript:;"> Latihan Soal </a>
                            </li>
                            <li>
                                <a href="javascript:;"> Galeri </a>
                            </li>
                            <li>
                                <a href="javascript:;"> Komentar </a>
                            </li>

                            <li class="divider"></li>
                            <li>
                                <a href="javascript:;"> Kembali</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="portlet yellow-crusta box">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-list"></i>Detail Pembelajaran
                                </div>

                            </div>
                            <div class="portlet-body">
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Mata Pelajaran :</div>
                                    <div class="col-md-7 value"> Matematika - Kelompok Umum</div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Tingkat:</div>
                                    <div class="col-md-7 value"> SMA SMK MA MAK</div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Kelas:</div>
                                    <div class="col-md-7 value"> X</div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Dibuat :</div>
                                    <div class="col-md-7 value"> 28 Juli 2016 14:00:00</div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Diedit terakhir :</div>
                                    <div class="col-md-7 value"> 30 Juli 2016 14:00:00</div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Rating:</div>
                                    <div class="col-md-3 value"><a href="javascript:;" class="btn btn-sm blue btn-outline">
                                            <i class="fa fa-thumbs-o-up"></i> 2.452</a></div>
                                    <div class="col-md-3 value"><a href="javascript:;" class="btn btn-sm red btn-outline">
                                            <i class="fa fa-thumbs-o-down"></i> 21</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="portlet blue-hoki box">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-user"></i>Penyusun
                                </div>
                            </div>
                            <div class="portlet-body ">
                                <div class="general-item-list">
                                    <div class="item">
                                        <div class="item-head">
                                            <div class="item-details">
                                                <img class="item-pic" src="https://dakrolak.files.wordpress.com/2015/06/jon-snow-4.jpg">
                                                <a href="" class="item-name primary-link">Jheon Targaryen</a>
                                                <span class="item-title">SMAN 5 Malang</span>
                                            </div>

                                                    <span class="item-status font-blue">
                                                        <i class="fa fa-check"></i> Peserta</span>
                                        </div>
                                        <div class="item-body"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                                            magna aliquam erat volutpat.
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Materi Pembelajaran </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                    <a href="" class="fullscreen"> </a>
                </div>

            </div>
            <div class="portlet-body">
                <div class="tab-content">
                    <div class="tab-pane active" id="portlet_tab_1">
                        <p> Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
                            praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                            magna aliquam erat volutpat.ut laoreet dolore magna ut laoreet dolore magna. ut laoreet dolore magna. ut laoreet dolore magna. </p>
                    </div>
                    <div class="tab-pane" id="portlet_tab_2">
                        <p> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
                            dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                            invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo. </p>
                    </div>
                    <div class="tab-pane" id="portlet_tab_3">
                        <p> Ut wisi enim ad btn-smm veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit
                            esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait
                            nulla facilisi. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}